name = "discord-bot-rust"
workers_dev = true
compatibility_date = "2023-05-18"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.17"

[build]
command = "cargo install -q worker-build && worker-build --release"