name = "discord-bot-rust"
workers_dev = true
compatibility_date = "2023-05-18"
account_id = "ba4e8f7f9ffbc23dba6acd0d9bd3ef46"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.17"

[[d1_databases]]
binding = 'DB'
database_name = 'wanderer-moe'
database_id = 'df7af4d9-3546-42d2-bf0d-8376091a7875'

[build]
command = "cargo install -q worker-build && worker-build --release"