name: Checks

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
    checks:
        name: Checks
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Format checks
          run: cargo fmt -- --check
        - name: Idiomatic checks
          run: cargo clippy -- -D warnings