name: Deploy to Cloudflare Workers

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy to Cloudflare Workers using Wrangler
              env:
                    CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
              run: npm i -g wrangler && npx wrangler publish

            - name: Curl the deployed Worker
              run: curl -X POST https://discord-bot-rust.dromzeh.workers.dev/register